<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class InitialDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seed Labor Costs
        DB::table('labor_costs')->insert([
            [
                'service_type' => 'Repair',
                'cost' => 80.00,
                'previous_cost' => null,
                'effective_date' => Carbon::now(),
                'modified_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_type' => 'Installation',
                'cost' => 150.00,
                'previous_cost' => null,
                'effective_date' => Carbon::now(),
                'modified_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_type' => 'Maintenance',
                'cost' => 60.00,
                'previous_cost' => null,
                'effective_date' => Carbon::now(),
                'modified_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        // Seed Technicians
        DB::table('technicians')->insert([
            [
                'name' => 'James Caraan',
                'phone' => '+63912-345-6789',
                'email' => 'james.caraan@example.com',
                'address' => 'Barangay 1-A, Tuguegarao City',
                'specializations' => json_encode(['Aircon', 'Refrigerator']),
                'status' => 'Available',
                'jobs_completed' => 127,
                'active_jobs' => 3,
                'average_rating' => 4.8,
                'total_revenue' => 28575.00,
                'date_hired' => '2024-01-15',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GB Labrador',
                'phone' => '+63912-345-6790',
                'email' => 'gb.labrador@example.com',
                'address' => 'Barangay 2-A, Tuguegarao City',
                'specializations' => json_encode(['Aircon', 'Refrigerator']),
                'status' => 'Available',
                'jobs_completed' => 98,
                'active_jobs' => 2,
                'average_rating' => 4.6,
                'total_revenue' => 22100.00,
                'date_hired' => '2024-03-20',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nonong Balinan',
                'phone' => '+63912-345-6791',
                'email' => 'nonong.balinan@example.com',
                'address' => 'Barangay 3-A, Tuguegarao City',
                'specializations' => json_encode(['Aircon']),
                'status' => 'Available',
                'jobs_completed' => 85,
                'active_jobs' => 1,
                'average_rating' => 4.5,
                'total_revenue' => 19250.00,
                'date_hired' => '2024-05-10',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ryan Rems',
                'phone' => '+63912-345-6792',
                'email' => 'ryan.rems@example.com',
                'address' => 'Barangay 4-A, Tuguegarao City',
                'specializations' => json_encode(['Refrigerator']),
                'status' => 'Off Duty',
                'jobs_completed' => 72,
                'active_jobs' => 0,
                'average_rating' => 4.4,
                'total_revenue' => 16200.00,
                'date_hired' => '2024-06-15',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Muman Reyes',
                'phone' => '+63912-345-6793',
                'email' => 'muman.reyes@example.com',
                'address' => 'Barangay 5-A, Tuguegarao City',
                'specializations' => json_encode(['Aircon', 'Refrigerator']),
                'status' => 'Available',
                'jobs_completed' => 65,
                'active_jobs' => 1,
                'average_rating' => 4.3,
                'total_revenue' => 14625.00,
                'date_hired' => '2024-08-01',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        // Seed Sample Inventory Items
        DB::table('inventory_items')->insert([
            // Aircon Spare Parts
            [
                'item_code' => 'AC-COMP-001',
                'name' => 'Aircon Compressor',
                'brand' => 'Samsung',
                'category' => 'Aircon Spare Parts',
                'description' => '1HP Compressor for split type aircon',
                'quantity' => 10,
                'reorder_point' => 3,
                'cost_price' => 3500.00,
                'selling_price' => 4200.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'AC-FAN-001',
                'name' => 'Aircon Fan Motor',
                'brand' => 'LG',
                'category' => 'Aircon Spare Parts',
                'description' => 'Indoor fan motor',
                'quantity' => 15,
                'reorder_point' => 5,
                'cost_price' => 850.00,
                'selling_price' => 1100.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'AC-CAP-001',
                'name' => 'Capacitor',
                'brand' => 'Generic',
                'category' => 'Aircon Spare Parts',
                'description' => '35uF running capacitor',
                'quantity' => 25,
                'reorder_point' => 10,
                'cost_price' => 120.00,
                'selling_price' => 180.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'AC-FILTER-001',
                'name' => 'Air Filter',
                'brand' => 'Generic',
                'category' => 'Aircon Spare Parts',
                'description' => 'Washable aircon filter',
                'quantity' => 30,
                'reorder_point' => 10,
                'cost_price' => 80.00,
                'selling_price' => 150.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'AC-REFRIG-001',
                'name' => 'Refrigerant R410A',
                'brand' => 'Honeywell',
                'category' => 'Aircon Spare Parts',
                'description' => 'R410A refrigerant gas 1kg',
                'quantity' => 18,
                'reorder_point' => 5,
                'cost_price' => 550.00,
                'selling_price' => 750.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'AC-COIL-001',
                'name' => 'Evaporator Coil',
                'brand' => 'LG',
                'category' => 'Aircon Spare Parts',
                'description' => 'Indoor evaporator coil',
                'quantity' => 8,
                'reorder_point' => 3,
                'cost_price' => 2200.00,
                'selling_price' => 2800.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'AC-PCB-001',
                'name' => 'Control Board PCB',
                'brand' => 'Samsung',
                'category' => 'Aircon Spare Parts',
                'description' => 'Universal control board',
                'quantity' => 12,
                'reorder_point' => 4,
                'cost_price' => 1800.00,
                'selling_price' => 2500.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'AC-DRAIN-001',
                'name' => 'Drain Pump',
                'brand' => 'Generic',
                'category' => 'Aircon Spare Parts',
                'description' => 'Condensate drain pump',
                'quantity' => 14,
                'reorder_point' => 5,
                'cost_price' => 350.00,
                'selling_price' => 550.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Refrigerator Spare Parts
            [
                'item_code' => 'REF-THERM-001',
                'name' => 'Thermostat',
                'brand' => 'Carrier',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Universal refrigerator thermostat',
                'quantity' => 20,
                'reorder_point' => 5,
                'cost_price' => 450.00,
                'selling_price' => 650.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'REF-COMP-001',
                'name' => 'Refrigerator Compressor',
                'brand' => 'Samsung',
                'category' => 'Refrigerator Spare Parts',
                'description' => '1/6HP compressor',
                'quantity' => 8,
                'reorder_point' => 3,
                'cost_price' => 2800.00,
                'selling_price' => 3500.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'REF-DOOR-001',
                'name' => 'Door Seal Gasket',
                'brand' => 'Generic',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Universal door gasket',
                'quantity' => 22,
                'reorder_point' => 8,
                'cost_price' => 280.00,
                'selling_price' => 450.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'REF-FAN-001',
                'name' => 'Evaporator Fan Motor',
                'brand' => 'LG',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Freezer fan motor',
                'quantity' => 16,
                'reorder_point' => 5,
                'cost_price' => 680.00,
                'selling_price' => 950.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'REF-TIMER-001',
                'name' => 'Defrost Timer',
                'brand' => 'Generic',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Universal defrost timer',
                'quantity' => 18,
                'reorder_point' => 6,
                'cost_price' => 320.00,
                'selling_price' => 500.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'REF-RELAY-001',
                'name' => 'Overload Relay',
                'brand' => 'Generic',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Compressor overload relay',
                'quantity' => 24,
                'reorder_point' => 8,
                'cost_price' => 150.00,
                'selling_price' => 250.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'REF-LIGHT-001',
                'name' => 'Interior Light Bulb',
                'brand' => 'Generic',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'LED interior light',
                'quantity' => 35,
                'reorder_point' => 12,
                'cost_price' => 80.00,
                'selling_price' => 150.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'REF-HEATER-001',
                'name' => 'Defrost Heater',
                'brand' => 'Samsung',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Evaporator defrost heater',
                'quantity' => 13,
                'reorder_point' => 5,
                'cost_price' => 420.00,
                'selling_price' => 650.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Aircon Units
            [
                'item_code' => 'AC-UNIT-WIN-1HP',
                'name' => 'Window Type Aircon 1HP',
                'brand' => 'Carrier',
                'category' => 'Aircon Unit',
                'description' => 'Brand new window type 1HP',
                'quantity' => 5,
                'reorder_point' => 2,
                'cost_price' => 12000.00,
                'selling_price' => 15000.00,
                'status' => 'In Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'AC-UNIT-SPLIT-1HP',
                'name' => 'Split Type Aircon 1HP',
                'brand' => 'Daikin',
                'category' => 'Aircon Unit',
                'description' => 'Brand new split type 1HP inverter',
                'quantity' => 3,
                'reorder_point' => 2,
                'cost_price' => 18000.00,
                'selling_price' => 22000.00,
                'status' => 'Low Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Refrigerator Units
            [
                'item_code' => 'REF-UNIT-SINGLE',
                'name' => 'Single Door Refrigerator',
                'brand' => 'Samsung',
                'category' => 'Refrigerator Unit',
                'description' => '5.5 cubic feet single door',
                'quantity' => 4,
                'reorder_point' => 2,
                'cost_price' => 8000.00,
                'selling_price' => 10500.00,
                'status' => 'Low Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'item_code' => 'REF-UNIT-DOUBLE',
                'name' => 'Double Door Refrigerator',
                'brand' => 'LG',
                'category' => 'Refrigerator Unit',
                'description' => '16 cubic feet double door inverter',
                'quantity' => 2,
                'reorder_point' => 1,
                'cost_price' => 22000.00,
                'selling_price' => 28000.00,
                'status' => 'Low Stock',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        // Seed Sample Customers
        $customers = [
            [
                'name' => 'Robin Scherbatsky',
                'phone' => '+63917-123-4567',
                'address' => 'Barangay 1-A, Tuguegarao City',
                'customer_since' => Carbon::now()->subMonths(6),
                'total_bookings' => 0,
                'total_spent' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ted Mosby',
                'phone' => '+63917-234-5678',
                'address' => 'Barangay 2-A, Tuguegarao City',
                'customer_since' => Carbon::now()->subMonths(8),
                'total_bookings' => 0,
                'total_spent' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Marshall Eriksen',
                'phone' => '+63917-345-6789',
                'address' => 'Barangay 3-A, Tuguegarao City',
                'customer_since' => Carbon::now()->subMonths(4),
                'total_bookings' => 0,
                'total_spent' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Barnabas Stinson',
                'phone' => '+63917-456-7890',
                'address' => 'Barangay 4-A, Tuguegarao City',
                'customer_since' => Carbon::now()->subMonths(3),
                'total_bookings' => 0,
                'total_spent' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lily Aldrin',
                'phone' => '+63917-567-8901',
                'address' => 'Barangay 5-A, Tuguegarao City',
                'customer_since' => Carbon::now()->subMonths(5),
                'total_bookings' => 0,
                'total_spent' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        DB::table('customers')->insert($customers);

        // Seed Sample Bookings
        DB::table('bookings')->insert([
            [
                'booking_number' => 'RP001',
                'customer_id' => 1, // Robin
                'technician_id' => 1, // James Caraan
                'appliance' => 'Aircon',
                'service_type' => 'Repair',
                'issue_description' => 'Aircon not cooling properly',
                'location' => 'Barangay 1-A',
                'service_date' => '2025-10-01',
                'service_time' => '10:00:00',
                'status' => 'Assigned',
                'labor_cost' => 80.00,
                'parts_cost' => 0,
                'total_amount' => 0,
                'assigned_at' => Carbon::now(),
                'completed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'booking_number' => 'INS001',
                'customer_id' => 2, // Ted
                'technician_id' => null,
                'appliance' => 'Aircon',
                'service_type' => 'Installation',
                'issue_description' => 'Install new split type aircon',
                'location' => 'Barangay 2-A',
                'service_date' => '2025-10-01',
                'service_time' => '12:00:00',
                'status' => 'Pending',
                'labor_cost' => 150.00,
                'parts_cost' => 0,
                'total_amount' => 0,
                'assigned_at' => null,
                'completed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'booking_number' => 'RP002',
                'customer_id' => 3, // Marshall
                'technician_id' => 2, // GB Labrador
                'appliance' => 'Aircon',
                'service_type' => 'Repair',
                'issue_description' => 'Aircon making loud noise',
                'location' => 'Barangay 3-A',
                'service_date' => '2025-10-01',
                'service_time' => '13:00:00',
                'status' => 'Assigned',
                'labor_cost' => 80.00,
                'parts_cost' => 0,
                'total_amount' => 0,
                'assigned_at' => Carbon::now(),
                'completed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'booking_number' => 'MN001',
                'customer_id' => 4, // Barnabas
                'technician_id' => null,
                'appliance' => 'Aircon',
                'service_type' => 'Maintenance',
                'issue_description' => 'Regular maintenance check',
                'location' => 'Barangay 4-A',
                'service_date' => '2025-10-02',
                'service_time' => '10:00:00',
                'status' => 'Pending',
                'labor_cost' => 60.00,
                'parts_cost' => 0,
                'total_amount' => 0,
                'assigned_at' => null,
                'completed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'booking_number' => 'RP003',
                'customer_id' => 5, // Lily
                'technician_id' => null,
                'appliance' => 'Refrigerator',
                'service_type' => 'Repair',
                'issue_description' => 'Refrigerator not cooling',
                'location' => 'Barangay 5-A',
                'service_date' => '2025-10-02',
                'service_time' => '11:00:00',
                'status' => 'Pending',
                'labor_cost' => 80.00,
                'parts_cost' => 0,
                'total_amount' => 0,
                'assigned_at' => null,
                'completed_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        echo "✅ Initial data seeded successfully!\n";
        echo "   - 3 Labor cost entries\n";
        echo "   - 5 Technicians\n";
        echo "   - 20 Inventory items (8 Aircon Spare Parts, 8 Refrigerator Spare Parts, 2 Aircon Unit, 2 Refrigerator Unit)\n";
        echo "   - 5 Customers\n";
        echo "   - 5 Bookings\n";
    }
}
