<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use App\Models\Booking;
use App\Models\Technician;
use App\Models\InventoryItem;
use Carbon\Carbon;

class TestDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create 10 Technicians (8 Available, 2 Off Duty)
        $technicians = [
            [
                'name' => 'Juan Dela Cruz',
                'phone' => '09171234567',
                'email' => 'juan.delacruz@coolsystem.com',
                'address' => 'Matina, Davao City',
                'specializations' => ['Air-conditioner', 'Refrigerator'],
                'status' => 'Available',
                'jobs_completed' => 150,
                'active_jobs' => 0,
                'average_rating' => 4.8,
                'total_revenue' => 250000.00,
                'date_hired' => Carbon::now()->subYears(3),
            ],
            [
                'name' => 'Maria Santos',
                'phone' => '09181234568',
                'email' => 'maria.santos@coolsystem.com',
                'address' => 'Ecoland, Davao City',
                'specializations' => ['Air-conditioner'],
                'status' => 'Available',
                'jobs_completed' => 120,
                'active_jobs' => 0,
                'average_rating' => 4.7,
                'total_revenue' => 180000.00,
                'date_hired' => Carbon::now()->subYears(2),
            ],
            [
                'name' => 'Pedro Garcia',
                'phone' => '09191234569',
                'email' => 'pedro.garcia@coolsystem.com',
                'address' => 'Buhangin, Davao City',
                'specializations' => ['Refrigerator'],
                'status' => 'Available',
                'jobs_completed' => 95,
                'active_jobs' => 0,
                'average_rating' => 4.6,
                'total_revenue' => 145000.00,
                'date_hired' => Carbon::now()->subYears(2),
            ],
            [
                'name' => 'Ana Reyes',
                'phone' => '09201234570',
                'email' => 'ana.reyes@coolsystem.com',
                'address' => 'Toril, Davao City',
                'specializations' => ['Air-conditioner', 'Refrigerator'],
                'status' => 'Available',
                'jobs_completed' => 180,
                'active_jobs' => 0,
                'average_rating' => 4.9,
                'total_revenue' => 320000.00,
                'date_hired' => Carbon::now()->subYears(4),
            ],
            [
                'name' => 'Carlos Ramos',
                'phone' => '09211234571',
                'email' => 'carlos.ramos@coolsystem.com',
                'address' => 'Panacan, Davao City',
                'specializations' => ['Air-conditioner'],
                'status' => 'Available',
                'jobs_completed' => 85,
                'active_jobs' => 0,
                'average_rating' => 4.5,
                'total_revenue' => 125000.00,
                'date_hired' => Carbon::now()->subYears(1),
            ],
            [
                'name' => 'Linda Cruz',
                'phone' => '09221234572',
                'email' => 'linda.cruz@coolsystem.com',
                'address' => 'Bajada, Davao City',
                'specializations' => ['Refrigerator'],
                'status' => 'Available',
                'jobs_completed' => 110,
                'active_jobs' => 0,
                'average_rating' => 4.7,
                'total_revenue' => 165000.00,
                'date_hired' => Carbon::now()->subYears(2),
            ],
            [
                'name' => 'Roberto Fernandez',
                'phone' => '09231234573',
                'email' => 'roberto.fernandez@coolsystem.com',
                'address' => 'Agdao, Davao City',
                'specializations' => ['Air-conditioner', 'Refrigerator'],
                'status' => 'Available',
                'jobs_completed' => 140,
                'active_jobs' => 0,
                'average_rating' => 4.8,
                'total_revenue' => 220000.00,
                'date_hired' => Carbon::now()->subYears(3),
            ],
            [
                'name' => 'Sofia Morales',
                'phone' => '09241234574',
                'email' => 'sofia.morales@coolsystem.com',
                'address' => 'Talomo, Davao City',
                'specializations' => ['Air-conditioner'],
                'status' => 'Available',
                'jobs_completed' => 75,
                'active_jobs' => 0,
                'average_rating' => 4.6,
                'total_revenue' => 110000.00,
                'date_hired' => Carbon::now()->subYear(),
            ],
            [
                'name' => 'Miguel Torres',
                'phone' => '09251234575',
                'email' => 'miguel.torres@coolsystem.com',
                'address' => 'Bunawan, Davao City',
                'specializations' => ['Refrigerator'],
                'status' => 'Off Duty',
                'jobs_completed' => 130,
                'active_jobs' => 0,
                'average_rating' => 4.7,
                'total_revenue' => 195000.00,
                'date_hired' => Carbon::now()->subYears(3),
            ],
            [
                'name' => 'Elena Jimenez',
                'phone' => '09261234576',
                'email' => 'elena.jimenez@coolsystem.com',
                'address' => 'Calinan, Davao City',
                'specializations' => ['Air-conditioner', 'Refrigerator'],
                'status' => 'Off Duty',
                'jobs_completed' => 160,
                'active_jobs' => 0,
                'average_rating' => 4.8,
                'total_revenue' => 275000.00,
                'date_hired' => Carbon::now()->subYears(4),
            ],
        ];

        foreach ($technicians as $techData) {
            Technician::create($techData);
        }

        // Create 20 Inventory Items
        $inventoryItems = [
            // Air-conditioner spare parts (8 items)
            [
                'item_code' => 'AC-CMP-001',
                'name' => 'AC Compressor 1HP',
                'brand' => 'Carrier',
                'category' => 'Aircon Spare Parts',
                'description' => '1 Horsepower compressor for split-type air conditioners',
                'quantity' => 15,
                'reorder_point' => 5,
                'cost_price' => 8500.00,
                'selling_price' => 12000.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'AC-FAN-002',
                'name' => 'AC Fan Motor',
                'brand' => 'LG',
                'category' => 'Aircon Spare Parts',
                'description' => 'Indoor fan motor for wall-mounted AC units',
                'quantity' => 20,
                'reorder_point' => 8,
                'cost_price' => 1200.00,
                'selling_price' => 1800.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'AC-CAP-003',
                'name' => 'AC Capacitor 50uF',
                'brand' => 'Nichicon',
                'category' => 'Aircon Spare Parts',
                'description' => '50 microfarad capacitor for AC compressor',
                'quantity' => 50,
                'reorder_point' => 15,
                'cost_price' => 250.00,
                'selling_price' => 450.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'AC-THM-004',
                'name' => 'AC Thermostat',
                'brand' => 'Samsung',
                'category' => 'Aircon Spare Parts',
                'description' => 'Digital thermostat for precise temperature control',
                'quantity' => 25,
                'reorder_point' => 10,
                'cost_price' => 800.00,
                'selling_price' => 1200.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'AC-FLT-005',
                'name' => 'AC Air Filter',
                'brand' => 'Universal',
                'category' => 'Aircon Spare Parts',
                'description' => 'Washable air filter for AC indoor units',
                'quantity' => 100,
                'reorder_point' => 30,
                'cost_price' => 150.00,
                'selling_price' => 300.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'AC-CND-006',
                'name' => 'AC Condenser Coil',
                'brand' => 'Daikin',
                'category' => 'Aircon Spare Parts',
                'description' => 'Outdoor condenser coil for 1.5HP AC units',
                'quantity' => 8,
                'reorder_point' => 3,
                'cost_price' => 5500.00,
                'selling_price' => 8000.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'AC-REM-007',
                'name' => 'AC Remote Control',
                'brand' => 'Universal',
                'category' => 'Aircon Spare Parts',
                'description' => 'Universal remote control compatible with most AC brands',
                'quantity' => 35,
                'reorder_point' => 12,
                'cost_price' => 450.00,
                'selling_price' => 750.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'AC-REF-008',
                'name' => 'R410A Refrigerant Gas',
                'brand' => 'Honeywell',
                'category' => 'Aircon Spare Parts',
                'description' => '13.6kg cylinder of R410A refrigerant',
                'quantity' => 12,
                'reorder_point' => 4,
                'cost_price' => 4200.00,
                'selling_price' => 6500.00,
                'status' => 'In Stock',
            ],
            
            // Refrigerator spare parts (8 items)
            [
                'item_code' => 'RF-CMP-009',
                'name' => 'Refrigerator Compressor',
                'brand' => 'Embraco',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Compressor for single-door refrigerators',
                'quantity' => 10,
                'reorder_point' => 4,
                'cost_price' => 4500.00,
                'selling_price' => 6500.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'RF-THM-010',
                'name' => 'Refrigerator Thermostat',
                'brand' => 'Ranco',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Temperature control thermostat',
                'quantity' => 30,
                'reorder_point' => 10,
                'cost_price' => 650.00,
                'selling_price' => 1000.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'RF-TMR-011',
                'name' => 'Defrost Timer',
                'brand' => 'Paragon',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Automatic defrost timer for frost-free refrigerators',
                'quantity' => 18,
                'reorder_point' => 6,
                'cost_price' => 850.00,
                'selling_price' => 1300.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'RF-FAN-012',
                'name' => 'Evaporator Fan Motor',
                'brand' => 'Universal',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Fan motor for refrigerator cooling circulation',
                'quantity' => 22,
                'reorder_point' => 8,
                'cost_price' => 1100.00,
                'selling_price' => 1650.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'RF-SEN-013',
                'name' => 'Door Switch Sensor',
                'brand' => 'Universal',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Door sensor switch for light control',
                'quantity' => 45,
                'reorder_point' => 15,
                'cost_price' => 120.00,
                'selling_price' => 250.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'RF-GAS-014',
                'name' => 'R134A Refrigerant',
                'brand' => 'DuPont',
                'category' => 'Refrigerator Spare Parts',
                'description' => '13.6kg cylinder of R134A refrigerant',
                'quantity' => 8,
                'reorder_point' => 3,
                'cost_price' => 3800.00,
                'selling_price' => 5800.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'RF-DSP-015',
                'name' => 'Water Dispenser Kit',
                'brand' => 'Samsung',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Complete water dispenser assembly',
                'quantity' => 12,
                'reorder_point' => 5,
                'cost_price' => 2200.00,
                'selling_price' => 3500.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'RF-GSK-016',
                'name' => 'Door Gasket Seal',
                'brand' => 'Universal',
                'category' => 'Refrigerator Spare Parts',
                'description' => 'Magnetic door seal gasket',
                'quantity' => 40,
                'reorder_point' => 15,
                'cost_price' => 550.00,
                'selling_price' => 900.00,
                'status' => 'In Stock',
            ],
            
            // Air-conditioner Units (2 items)
            [
                'item_code' => 'AC-UNT-017',
                'name' => 'Split Type AC 1.5HP',
                'brand' => 'Carrier',
                'category' => 'Aircon Unit',
                'description' => '1.5 Horsepower inverter split-type air conditioner',
                'quantity' => 5,
                'reorder_point' => 2,
                'cost_price' => 22000.00,
                'selling_price' => 32000.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'AC-UNT-018',
                'name' => 'Window Type AC 1HP',
                'brand' => 'LG',
                'category' => 'Aircon Unit',
                'description' => '1 Horsepower window-type air conditioner',
                'quantity' => 3,
                'reorder_point' => 1,
                'cost_price' => 15000.00,
                'selling_price' => 21000.00,
                'status' => 'In Stock',
            ],
            
            // Refrigerator Units (2 items)
            [
                'item_code' => 'RF-UNT-019',
                'name' => 'Two-Door Refrigerator 16cu.ft',
                'brand' => 'Samsung',
                'category' => 'Refrigerator Unit',
                'description' => '16 cubic feet two-door refrigerator with inverter',
                'quantity' => 4,
                'reorder_point' => 1,
                'cost_price' => 28000.00,
                'selling_price' => 38000.00,
                'status' => 'In Stock',
            ],
            [
                'item_code' => 'RF-UNT-020',
                'name' => 'Single Door Refrigerator 7cu.ft',
                'brand' => 'Condura',
                'category' => 'Refrigerator Unit',
                'description' => '7 cubic feet single-door refrigerator',
                'quantity' => 6,
                'reorder_point' => 2,
                'cost_price' => 12000.00,
                'selling_price' => 16500.00,
                'status' => 'In Stock',
            ],
        ];

        foreach ($inventoryItems as $itemData) {
            InventoryItem::create($itemData);
        }

        // Create 7 Customers for the bookings
        $customers = [
            [
                'name' => 'Mark Johnson',
                'phone' => '09171112233',
                'address' => 'Block 5 Lot 12, Paradise Village, Matina Davao City',
                'customer_since' => Carbon::now()->subMonths(6),
                'total_bookings' => 1,
                'total_spent' => 0,
            ],
            [
                'name' => 'Sarah Williams',
                'phone' => '09182223344',
                'address' => '45 Bonifacio Street, Poblacion District, Davao City',
                'customer_since' => Carbon::now()->subMonths(3),
                'total_bookings' => 1,
                'total_spent' => 0,
            ],
            [
                'name' => 'David Chen',
                'phone' => '09193334455',
                'address' => 'Unit 302 Camella Homes, Ecoland Davao City',
                'customer_since' => Carbon::now()->subYear(),
                'total_bookings' => 1,
                'total_spent' => 0,
            ],
            [
                'name' => 'Jennifer Lopez',
                'phone' => '09204445566',
                'address' => '78 Roxas Avenue, Downtown Davao City',
                'customer_since' => Carbon::now()->subMonths(8),
                'total_bookings' => 1,
                'total_spent' => 0,
            ],
            [
                'name' => 'Robert Taylor',
                'phone' => '09215556677',
                'address' => 'Phase 2 Block 8, Somo Subdivision, Buhangin Davao City',
                'customer_since' => Carbon::now()->subMonths(4),
                'total_bookings' => 1,
                'total_spent' => 0,
            ],
            [
                'name' => 'Michelle Anderson',
                'phone' => '09226667788',
                'address' => '123 Quirino Avenue, Ma-a Davao City',
                'customer_since' => Carbon::now()->subMonths(2),
                'total_bookings' => 1,
                'total_spent' => 0,
            ],
            [
                'name' => 'James Martinez',
                'phone' => '09237778899',
                'address' => 'Lot 15 Green Valley Homes, Toril Davao City',
                'customer_since' => Carbon::now()->subMonths(5),
                'total_bookings' => 1,
                'total_spent' => 0,
            ],
        ];

        $createdCustomers = [];
        foreach ($customers as $customerData) {
            $createdCustomers[] = Customer::create($customerData);
        }

        // Create 7 Pending Bookings
        $bookings = [
            [
                'customer_id' => $createdCustomers[0]->id,
                'appliance' => 'Aircon',
                'service_type' => 'Repair',
                'issue_description' => 'Not cooling properly, weak airflow from the unit',
                'location' => 'Block 5 Lot 12, Paradise Village, Matina Davao City',
                'service_date' => Carbon::now()->addDays(2),
                'service_time' => '09:00:00',
                'status' => 'Pending',
            ],
            [
                'customer_id' => $createdCustomers[1]->id,
                'appliance' => 'Refrigerator',
                'service_type' => 'Repair',
                'issue_description' => 'Freezer not freezing, ice melting inside',
                'location' => '45 Bonifacio Street, Poblacion District, Davao City',
                'service_date' => Carbon::now()->addDays(3),
                'service_time' => '10:00:00',
                'status' => 'Pending',
            ],
            [
                'customer_id' => $createdCustomers[2]->id,
                'appliance' => 'Aircon',
                'service_type' => 'Installation',
                'issue_description' => 'New 1.5HP split-type AC unit needs installation in bedroom',
                'location' => 'Unit 302 Camella Homes, Ecoland Davao City',
                'service_date' => Carbon::now()->addDays(4),
                'service_time' => '14:00:00',
                'status' => 'Pending',
            ],
            [
                'customer_id' => $createdCustomers[3]->id,
                'appliance' => 'Refrigerator',
                'service_type' => 'Maintenance',
                'issue_description' => 'Regular cleaning and maintenance check, making strange noise',
                'location' => '78 Roxas Avenue, Downtown Davao City',
                'service_date' => Carbon::now()->addDays(5),
                'service_time' => '11:00:00',
                'status' => 'Pending',
            ],
            [
                'customer_id' => $createdCustomers[4]->id,
                'appliance' => 'Aircon',
                'service_type' => 'Maintenance',
                'issue_description' => 'General cleaning and freon check, AC is 2 years old',
                'location' => 'Phase 2 Block 8, Somo Subdivision, Buhangin Davao City',
                'service_date' => Carbon::now()->addDays(6),
                'service_time' => '13:00:00',
                'status' => 'Pending',
            ],
            [
                'customer_id' => $createdCustomers[5]->id,
                'appliance' => 'Refrigerator',
                'service_type' => 'Repair',
                'issue_description' => 'Water leaking from bottom, door seal seems loose',
                'location' => '123 Quirino Avenue, Ma-a Davao City',
                'service_date' => Carbon::now()->addDays(7),
                'service_time' => '15:00:00',
                'status' => 'Pending',
            ],
            [
                'customer_id' => $createdCustomers[6]->id,
                'appliance' => 'Aircon',
                'service_type' => 'Repair',
                'issue_description' => 'Remote control not working, AC turns on but wont respond to settings',
                'location' => 'Lot 15 Green Valley Homes, Toril Davao City',
                'service_date' => Carbon::now()->addDays(8),
                'service_time' => '16:00:00',
                'status' => 'Pending',
            ],
        ];

        foreach ($bookings as $bookingData) {
            // Generate unique booking number
            $bookingData['booking_number'] = 'BK-' . strtoupper(substr(md5(uniqid(rand(), true)), 0, 8));
            Booking::create($bookingData);
        }

        $this->command->info('✓ Created 10 technicians (8 Available, 2 Off Duty)');
        $this->command->info('✓ Created 20 inventory items');
        $this->command->info('✓ Created 7 customers');
        $this->command->info('✓ Created 7 pending bookings');
    }
}
